version: '3'

tasks:
  build:
    cmds:
      - docker compose -f docker-compose.yaml build
  run:
    cmds:
      - docker compose -f docker-compose.yaml up -d
  stop:
    cmds:
      - docker compose -f docker-compose.yaml down
